INSERT INTO `submenu` (`id`, `name`, `link`, `menu`, `target`) VALUES
('', '<i class=''fa fa-align-justify''></i> Blog', 'http://blog.megasoft-id.com', '2', '_blank'),
('', '<i class=''fa fa-cloud-upload''></i> File Hosting', 'http://files.megasoft-id.com', '2', '_blank'),
('', 'About Me', 'http://www.mas-dewa.com', '3', '_blank'),
('', 'About Us', 'http://about.megasoft-id.com', '3', '_selft'),
('', 'About Danang', 'http://about.megasoft-id.com/Danang', '3', '_selft'),
('', '<i class=''fa fa-laptop''></i> TV Online', 'http://tv.olvies.com', '2', '_selft'),
('', 'Dewafiles', 'http://loncat.in/dwfS', '5', '_selft'),
('', 'Mega Blogging', 'http://loncat.in/mgb', '5', '_selft'),
('', '<i class=''fa fa-film''></i> Movies', 'http://olvies.com', '2', '_blank'),
('', 'SMK Antivir', 'http://loncat.in/smk', '5', '_blank'),
('', '<i class=''fa fa-facebook''></i> Facebook', 'http://facebook.com/dewa.bagass.3', '6', '_blank'),
('', '<i class=''fa fa fa fa-twitter''></i> Twitter', 'https://twitter.com/Dewa_1995', '6', '_blank'),
('', '<i class=''fa fa-google-plus''></i> Google ++', 'https://google.com/+DewaBagasKara1995', '7', '_blank'),
('', '<i class=''fa fa-github''></i> Github', 'http://go.mas-dewa.com/github', '6', '_blank'),
('', '<i class=''fa fa-book''></i> Ebooks', 'http://blog.megasoft.com/label/ebooks/', '2', '_self'),
('', '<i class=''fa fa-picture-o''></i> Photo Gallery', 'http://photo.megasoft-id.com', '2', '_self'),
('', '<i class=''fa fa-cloud''></i> Web Hosting', 'http://bintanghost.com', '2', '_self'),
('', 'About Megasoft', '$url_gue/go/pages/1', '3', '_self'),
('', 'Another Products', 'http://megasoft-id.com/products.html', '5', '_blank');